2019-07-22 14:59:10,539 - DEBUG - tty.usbmodem0006822145041: Writing: 105 bytearray(b'\x8cG.o\xa0\xab\x98\xb5\xc0]\xa5C\xc4\nj\x12|\x8e\xcf\x94a>q\xe5\x9c\xc9>\xf6]k;\xf8L\x82\x96\xcfCi\no\xa3\xd1\x89\xbe\x0e\x00\x9c\x8c?A2b\x06U\xb0\xab;\x92\xd9\xf3\xf6*\xad\xe5\x8ez\x7f\xe8\xe6|\xc8\xd3\xac\x95"w\xb2\xc3\xb5\x99[\xeb\xf6\x0b\x01\xa9\xa7\x05\x8eG_\xe22\x0e\xd2\x8f')
2019-07-22 14:59:10,540 - DEBUG - tty.usbmodem0006822145041: TX: 61698c472e6fa0ab98b5c05da543c40a6a127c8ecf94613e71e59cc93ef65d6b3bf84c8296cf43690a6fa3d189be0e009c8c3f4132620655b0ab3b92d9f3f62aade58e7a7fe8e67cc8d3ac952277b2c3b5995bebf60b01a9a7058e475fe2320ed28f
2019-07-22 14:59:10,542 - INFO - tty.usbmodem0006822145041: 

2019-07-22 14:59:10,542 - INFO - tty.usbmodem0006822145041: Sending next message
2019-07-22 14:59:10,554 - DEBUG - tty.usbmodem0006822145041: RX: 03845384
2019-07-22 14:59:10,554 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 83, 'status': 132, 'data': bytearray(b'')}}
2019-07-22 14:59:10,554 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-22 14:59:10,554 - DEBUG - tty.usbmodem0006822145041: Writing: 159 bytearray(b'\x01\x00\x01\x00')
2019-07-22 14:59:10,555 - DEBUG - tty.usbmodem0006822145041: TX: 059f01000100
2019-07-22 14:59:10,555 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-22 14:59:10,556 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-22 14:59:10,556 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-22 14:59:10,556 - DEBUG - tty.usbmodem0006822145041: Writing: 146 bytearray(b'\x00\x00\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12')
2019-07-22 14:59:10,556 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-22 14:59:10,570 - DEBUG - tty.usbmodem0006822145041: TX: 1392000018eed9c2a56add85049ffc3c59ad0e12
2019-07-22 14:59:10,571 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-22 14:59:10,572 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-22 14:59:10,572 - DEBUG - tty.usbmodem0006822145041: Writing: 151 bytearray(b'\x00\x00\x00\x00Oh\xad\x85\xd9\xf4\x8a\xc8X\x9d\xf6e\xb6\xb4\x9b\x8a')
2019-07-22 14:59:10,573 - DEBUG - tty.usbmodem0006822145041: TX: 1597000000004f68ad85d9f48ac8589df665b6b49b8a
2019-07-22 14:59:10,574 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-22 14:59:10,574 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-22 14:59:10,575 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-22 14:59:10,576 - DEBUG - tty.usbmodem0006822145041: Writing: 151 bytearray(b'\x01\x00\x00\x00*\xa2\xa6\xde\xd5\xa0y\x8c\xea\xb5x|\xa3\xae9\xfc')
2019-07-22 14:59:10,576 - DEBUG - tty.usbmodem0006822145041: TX: 1597010000002aa2a6ded5a0798ceab5787ca3ae39fc
2019-07-22 14:59:10,576 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-22 14:59:10,577 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-22 14:59:10,577 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-22 14:59:10,578 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-22 14:59:10,578 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-22 14:59:10,578 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-22 14:59:10,579 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-22 14:59:10,579 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-22 14:59:10,579 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-22 14:59:10,579 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-22 14:59:10,579 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-22 14:59:10,579 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-22 14:59:10,579 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-22 14:59:10,580 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-22 14:59:10,580 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-22 14:59:10,580 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-22 14:59:10,580 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-22 14:59:10,580 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-22 14:59:10,580 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-22 14:59:10,580 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-22 14:59:10,580 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-22 14:59:10,581 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-22 14:59:10,581 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-22 14:59:10,581 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-22 14:59:10,581 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-07-22 14:59:10,581 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-07-22 14:59:10,581 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-07-22 14:59:10,581 - DEBUG - tty.usbmodem0006822145041: RX: 03849f00
2019-07-22 14:59:10,581 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 159, 'status': 0, 'data': bytearray(b'')}}
2019-07-22 14:59:10,581 - INFO - tty.usbmodem0006822145041: Success
2019-07-22 14:59:10,582 - DEBUG - tty.usbmodem0006822145041: RX: 058492000000
2019-07-22 14:59:10,582 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 146, 'status': 0, 'data': bytearray(b'\x00\x00')}}
2019-07-22 14:59:10,582 - INFO - tty.usbmodem0006822145041: SubnetAdd: {'subnet_handle': 0}
2019-07-22 14:59:10,582 - DEBUG - tty.usbmodem0006822145041: RX: 058497000000
2019-07-22 14:59:10,582 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 151, 'status': 0, 'data': bytearray(b'\x00\x00')}}
2019-07-22 14:59:10,582 - INFO - tty.usbmodem0006822145041: AppkeyAdd: {'appkey_handle': 0}
2019-07-22 14:59:10,582 - DEBUG - tty.usbmodem0006822145041: RX: 058497000100
2019-07-22 14:59:10,582 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 151, 'status': 0, 'data': bytearray(b'\x01\x00')}}
2019-07-22 14:59:10,582 - INFO - tty.usbmodem0006822145041: AppkeyAdd: {'appkey_handle': 1}
2019-07-22 14:59:14,545 - INFO - tty.usbmodem0006822145041: Timout handler timeout
2019-07-22 14:59:15,834 - DEBUG - tty.usbmodem0006822145041: Writing: 97 bytearray(b'')
2019-07-22 14:59:15,835 - DEBUG - tty.usbmodem0006822145041: TX: 0161
2019-07-22 14:59:15,840 - DEBUG - tty.usbmodem0006822145041: RX: 03846100
2019-07-22 14:59:15,840 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 97, 'status': 0, 'data': bytearray(b'')}}
2019-07-22 14:59:15,841 - INFO - tty.usbmodem0006822145041: Success
2019-07-22 14:59:16,017 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d50001c8639509c2c2
2019-07-22 14:59:16,018 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -43, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:16,018 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -43, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:16,018 - INFO - tty.usbmodem0006822145041: Received UUID 9db77a0526b8734988639509c242d107 with RSSI: -43 dB
2019-07-22 14:59:16,019 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:16,021 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasatrr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 14:59:18,021 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d80001c8639509c2c2
2019-07-22 14:59:18,021 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -40, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:18,022 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -40, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:18,022 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:18,022 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasatrr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 14:59:20,029 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d80001c8639509c2c2
2019-07-22 14:59:20,030 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -40, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:20,030 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -40, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:20,030 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:20,030 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasatrr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 14:59:22,040 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d40001c8639509c2c2
2019-07-22 14:59:22,040 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -44, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:22,040 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -44, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:22,040 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:22,041 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasatrr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 14:59:24,041 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d80001c8639509c2c2
2019-07-22 14:59:24,042 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -40, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:24,042 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -40, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:24,042 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:24,043 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasatrr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 14:59:26,042 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d80001c8639509c2c2
2019-07-22 14:59:26,042 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -40, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:26,042 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -40, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:26,043 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:26,043 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasatrr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 14:59:28,045 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d60001c8639509c2c2
2019-07-22 14:59:28,047 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -42, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:28,047 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -42, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:28,047 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:28,047 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasatrr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 14:59:32,059 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d80001c8639509c2c2
2019-07-22 14:59:32,064 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -40, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:32,065 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -40, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:32,065 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:32,066 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasatrr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 14:59:34,066 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d50001c8639509c2c2
2019-07-22 14:59:34,066 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -43, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:34,066 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -43, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:34,066 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:34,068 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasatrr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 14:59:36,070 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d70001c8639509c2c2
2019-07-22 14:59:36,070 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -41, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:36,070 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -41, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:36,070 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:36,071 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasatrr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 14:59:38,076 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d90001c8639509c2c2
2019-07-22 14:59:38,076 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -39, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:38,077 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -39, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:38,077 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:38,077 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasatrr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 14:59:40,084 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d50001c8639509c2c2
2019-07-22 14:59:40,084 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -43, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:40,084 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -43, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:40,084 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:40,085 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasatrr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 14:59:42,086 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d80001c8639509c2c2
2019-07-22 14:59:42,086 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -40, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:42,086 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -40, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:42,087 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:42,087 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasatrr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 14:59:44,096 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d80001c8639509c2c2
2019-07-22 14:59:44,101 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -40, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:44,101 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -40, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:44,101 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:44,102 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasatrr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 14:59:46,098 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d40001c8639509c2c2
2019-07-22 14:59:46,098 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -44, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:46,099 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -44, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:46,099 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:46,100 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasatrr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 14:59:48,101 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d60001c8639509c2c2
2019-07-22 14:59:48,101 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -42, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:48,102 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -42, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:48,102 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:48,102 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasatrr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 14:59:50,108 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d80001c8639509c2c2
2019-07-22 14:59:50,108 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -40, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:50,109 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -40, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:50,109 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:50,109 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasatrr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 14:59:52,114 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d60001c8639509c2c2
2019-07-22 14:59:52,115 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -42, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:52,115 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -42, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:52,115 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:52,116 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasattr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 14:59:54,123 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d90001c8639509c2c2
2019-07-22 14:59:54,123 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -39, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:54,123 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -39, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:54,124 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:54,124 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasattr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 14:59:56,132 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d90001c8639509c2c2
2019-07-22 14:59:56,133 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -39, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:56,134 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -39, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:56,134 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:56,134 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasattr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 14:59:58,155 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d50001c8639509c2c2
2019-07-22 14:59:58,156 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -43, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:58,156 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -43, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 14:59:58,156 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 14:59:58,160 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasattr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 15:00:00,138 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d80001c8639509c2c2
2019-07-22 15:00:00,139 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -40, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 15:00:00,139 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -40, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 15:00:00,139 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 15:00:00,140 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasattr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 15:00:02,142 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d80001c8639509c2c2
2019-07-22 15:00:02,143 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -40, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 15:00:02,143 - INFO - tty.usbmodem0006822145041: {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -40, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-07-22 15:00:02,143 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.newUnProvisionedDeviceEventHandler of <interactive_pyaci.Manager object at 0x10ec45f98>>
2019-07-22 15:00:02,143 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 334, in newUnProvisionedDeviceEventHandler
    if hasattr(self, onNewUnProvisionedDevice):
NameError: name 'hasatrr' is not defined

2019-07-22 15:00:03,381 - DEBUG - tty.usbmodem0006822145041: exited read event
