2019-06-25 17:01:31,108 - DEBUG - tty.usbmodem0006822145041: Writing: 105 bytearray(b'bm\x01"f\xfd4y\xf3aP\xd3y\xbc\x98\xc8\xfd\x96a>\xeex\t\xd1\xa4\xeb\x7f\x10}\x9a\x0c\xa2S\xc4\xa8\xfe\x06\xdd\xa2\xbd\xcdN\x1es]\x17C`\xa07`M\x8b$\x13\x08\xad\xbc\x18\xa3\xe6P\x82\xfb\xbf\xffx\xa4X]\'\x01\x8c\xe8G\x87\xa0\x83\x821\x13\x02\xa1m^K\x1c\x92\xb3\x82\x8f\xad\xd8%\xd0|')
2019-06-25 17:01:31,108 - DEBUG - tty.usbmodem0006822145041: TX: 6169626d012266fd3479f36150d379bc98c8fd96613eee7809d1a4eb7f107d9a0ca253c4a8fe06dda2bdcd4e1e735d174360a037604d8b241308adbc18a3e65082fbbfff78a4585d27018ce84787a08382311302a16d5e4b1c92b3828fadd825d07c
2019-06-25 17:01:31,118 - DEBUG - tty.usbmodem0006822145041: RX: 03845384
2019-06-25 17:01:31,118 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 83, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:01:31,118 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:01:31,118 - DEBUG - tty.usbmodem0006822145041: Writing: 159 bytearray(b'\x01\x00\x01\x00')
2019-06-25 17:01:31,118 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1073fa4a8>>
2019-06-25 17:01:31,119 - DEBUG - tty.usbmodem0006822145041: TX: 059f01000100
2019-06-25 17:01:31,120 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 217, in __event_handler
    self.echo({"data": event.__oopcode})
AttributeError: 'CmdRsp' object has no attribute '_Manager__oopcode'

2019-06-25 17:01:31,121 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:01:31,121 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:01:31,121 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:01:31,121 - DEBUG - tty.usbmodem0006822145041: Writing: 146 bytearray(b'\x00\x00\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12')
2019-06-25 17:01:31,122 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1073fa4a8>>
2019-06-25 17:01:31,122 - DEBUG - tty.usbmodem0006822145041: TX: 1392000018eed9c2a56add85049ffc3c59ad0e12
2019-06-25 17:01:31,123 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 217, in __event_handler
    self.echo({"data": event.__oopcode})
AttributeError: 'CmdRsp' object has no attribute '_Manager__oopcode'

2019-06-25 17:01:31,124 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:01:31,125 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:01:31,126 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:01:31,126 - DEBUG - tty.usbmodem0006822145041: Writing: 151 bytearray(b'\x00\x00\x00\x00Oh\xad\x85\xd9\xf4\x8a\xc8X\x9d\xf6e\xb6\xb4\x9b\x8a')
2019-06-25 17:01:31,127 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1073fa4a8>>
2019-06-25 17:01:31,127 - DEBUG - tty.usbmodem0006822145041: TX: 1597000000004f68ad85d9f48ac8589df665b6b49b8a
2019-06-25 17:01:31,127 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 217, in __event_handler
    self.echo({"data": event.__oopcode})
AttributeError: 'CmdRsp' object has no attribute '_Manager__oopcode'

2019-06-25 17:01:31,128 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:01:31,128 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:01:31,128 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:01:31,128 - DEBUG - tty.usbmodem0006822145041: Writing: 151 bytearray(b'\x01\x00\x00\x00*\xa2\xa6\xde\xd5\xa0y\x8c\xea\xb5x|\xa3\xae9\xfc')
2019-06-25 17:01:31,128 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1073fa4a8>>
2019-06-25 17:01:31,128 - DEBUG - tty.usbmodem0006822145041: TX: 1597010000002aa2a6ded5a0798ceab5787ca3ae39fc
2019-06-25 17:01:31,128 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 217, in __event_handler
    self.echo({"data": event.__oopcode})
AttributeError: 'CmdRsp' object has no attribute '_Manager__oopcode'

2019-06-25 17:01:31,129 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:01:31,129 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:01:31,129 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:01:31,129 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1073fa4a8>>
2019-06-25 17:01:31,129 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 217, in __event_handler
    self.echo({"data": event.__oopcode})
AttributeError: 'CmdRsp' object has no attribute '_Manager__oopcode'

2019-06-25 17:01:31,130 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:01:31,147 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:01:31,147 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:01:31,147 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1073fa4a8>>
2019-06-25 17:01:31,148 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 217, in __event_handler
    self.echo({"data": event.__oopcode})
AttributeError: 'CmdRsp' object has no attribute '_Manager__oopcode'

2019-06-25 17:01:31,148 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:01:31,148 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:01:31,150 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:01:31,151 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1073fa4a8>>
2019-06-25 17:01:31,153 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 217, in __event_handler
    self.echo({"data": event.__oopcode})
AttributeError: 'CmdRsp' object has no attribute '_Manager__oopcode'

2019-06-25 17:01:31,153 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:01:31,153 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:01:31,154 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:01:31,154 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1073fa4a8>>
2019-06-25 17:01:31,154 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 217, in __event_handler
    self.echo({"data": event.__oopcode})
AttributeError: 'CmdRsp' object has no attribute '_Manager__oopcode'

2019-06-25 17:01:31,154 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:01:31,154 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:01:31,154 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:01:31,154 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1073fa4a8>>
2019-06-25 17:01:31,155 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 217, in __event_handler
    self.echo({"data": event.__oopcode})
AttributeError: 'CmdRsp' object has no attribute '_Manager__oopcode'

2019-06-25 17:01:31,155 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:01:31,155 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:01:31,155 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:01:31,155 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1073fa4a8>>
2019-06-25 17:01:31,155 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 217, in __event_handler
    self.echo({"data": event.__oopcode})
AttributeError: 'CmdRsp' object has no attribute '_Manager__oopcode'

2019-06-25 17:01:31,155 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:01:31,155 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:01:31,155 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:01:31,156 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1073fa4a8>>
2019-06-25 17:01:31,156 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 217, in __event_handler
    self.echo({"data": event.__oopcode})
AttributeError: 'CmdRsp' object has no attribute '_Manager__oopcode'

2019-06-25 17:01:31,156 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:01:31,156 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:01:31,156 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:01:31,156 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1073fa4a8>>
2019-06-25 17:01:31,156 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 217, in __event_handler
    self.echo({"data": event.__oopcode})
AttributeError: 'CmdRsp' object has no attribute '_Manager__oopcode'

2019-06-25 17:01:31,157 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:01:31,157 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:01:31,158 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:01:31,158 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1073fa4a8>>
2019-06-25 17:01:31,158 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 217, in __event_handler
    self.echo({"data": event.__oopcode})
AttributeError: 'CmdRsp' object has no attribute '_Manager__oopcode'

2019-06-25 17:01:31,158 - DEBUG - tty.usbmodem0006822145041: RX: 03849f8e
2019-06-25 17:01:31,158 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 159, 'status': 142, 'data': bytearray(b'')}}
2019-06-25 17:01:31,158 - ERROR - tty.usbmodem0006822145041: None: ERROR_REJECTED
2019-06-25 17:01:31,158 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1073fa4a8>>
2019-06-25 17:01:31,159 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 217, in __event_handler
    self.echo({"data": event.__oopcode})
AttributeError: 'CmdRsp' object has no attribute '_Manager__oopcode'

2019-06-25 17:01:31,159 - DEBUG - tty.usbmodem0006822145041: RX: 03849281
2019-06-25 17:01:31,159 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 146, 'status': 129, 'data': bytearray(b'')}}
2019-06-25 17:01:31,159 - ERROR - tty.usbmodem0006822145041: SubnetAdd: ERROR_INTERNAL
2019-06-25 17:01:31,159 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1073fa4a8>>
2019-06-25 17:01:31,159 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 217, in __event_handler
    self.echo({"data": event.__oopcode})
AttributeError: 'CmdRsp' object has no attribute '_Manager__oopcode'

2019-06-25 17:01:31,159 - DEBUG - tty.usbmodem0006822145041: RX: 03849781
2019-06-25 17:01:31,159 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 151, 'status': 129, 'data': bytearray(b'')}}
2019-06-25 17:01:31,160 - ERROR - tty.usbmodem0006822145041: AppkeyAdd: ERROR_INTERNAL
2019-06-25 17:01:31,160 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1073fa4a8>>
2019-06-25 17:01:31,160 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 217, in __event_handler
    self.echo({"data": event.__oopcode})
AttributeError: 'CmdRsp' object has no attribute '_Manager__oopcode'

2019-06-25 17:01:31,160 - DEBUG - tty.usbmodem0006822145041: RX: 03849781
2019-06-25 17:01:31,160 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 151, 'status': 129, 'data': bytearray(b'')}}
2019-06-25 17:01:31,160 - ERROR - tty.usbmodem0006822145041: AppkeyAdd: ERROR_INTERNAL
2019-06-25 17:01:31,160 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1073fa4a8>>
2019-06-25 17:01:31,160 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 217, in __event_handler
    self.echo({"data": event.__oopcode})
AttributeError: 'CmdRsp' object has no attribute '_Manager__oopcode'

